sudo: false

language: node_js

branches:
  only:
    - master

node_js:
  - "6"

os:
  - osx
  - linux

before_script:
 - npm install varstream svgicons2svgfont node-gyp ttf2woff2 -g

script: npm run travis:test

